// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using efc.Subdomains.FeatureFlags;

#nullable disable

namespace efc.Migrations
{
    [DbContext(typeof(FeatureFlagsDbContext))]
    [Migration("20260214083439_Fix")]
    partial class Fix
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("efc.Subdomains.FeatureFlags.FeatureFlag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("EnabledOn")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedOnUtc")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("FeatureFlags");
                });

            modelBuilder.Entity("efc.Subdomains.FeatureFlags.FeatureFlagUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("FeatureFlagUsers");
                });

            modelBuilder.Entity("efc.Subdomains.FeatureFlags.FeatureFlagUserAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AssignedOnUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("FeatureFlagId")
                        .HasColumnType("int");

                    b.Property<int>("FeatureFlagUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FeatureFlagId");

                    b.HasIndex("FeatureFlagUserId");

                    b.ToTable("FeatureFlagAssignments");
                });

            modelBuilder.Entity("efc.Subdomains.FeatureFlags.FeatureFlagUserAssignment", b =>
                {
                    b.HasOne("efc.Subdomains.FeatureFlags.FeatureFlag", null)
                        .WithMany("UserAssignments")
                        .HasForeignKey("FeatureFlagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("efc.Subdomains.FeatureFlags.FeatureFlagUser", null)
                        .WithMany("FeatureFlagAssignments")
                        .HasForeignKey("FeatureFlagUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("efc.Subdomains.FeatureFlags.FeatureFlag", b =>
                {
                    b.Navigation("UserAssignments");
                });

            modelBuilder.Entity("efc.Subdomains.FeatureFlags.FeatureFlagUser", b =>
                {
                    b.Navigation("FeatureFlagAssignments");
                });
#pragma warning restore 612, 618
        }
    }
}
