// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using efc.Database;

#nullable disable

namespace efc.Migrations
{
    [DbContext(typeof(FeatureFlagsDbContext))]
    partial class FeatureFlagsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("efc.Database.FeatureFlag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("EnabledOn")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("UpdatedOnUtc")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("FeatureFlags");
                });

            modelBuilder.Entity("efc.Database.FeatureFlagUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("FeatureFlagUsers");
                });

            modelBuilder.Entity("efc.Database.FeatureFlagUserAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AssignedOnUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("FeatureFlagId")
                        .HasColumnType("int");

                    b.Property<int>("FeatureFlagUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FeatureFlagId");

                    b.HasIndex("FeatureFlagUserId");

                    b.ToTable("FeatureFlagAssignments");
                });

            modelBuilder.Entity("efc.Database.FeatureFlagUserAssignment", b =>
                {
                    b.HasOne("efc.Database.FeatureFlag", "FeatureFlag")
                        .WithMany("UserAssignments")
                        .HasForeignKey("FeatureFlagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("efc.Database.FeatureFlagUser", "FeatureFlagUser")
                        .WithMany("FeatureFlagAssignments")
                        .HasForeignKey("FeatureFlagUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FeatureFlag");

                    b.Navigation("FeatureFlagUser");
                });

            modelBuilder.Entity("efc.Database.FeatureFlag", b =>
                {
                    b.Navigation("UserAssignments");
                });

            modelBuilder.Entity("efc.Database.FeatureFlagUser", b =>
                {
                    b.Navigation("FeatureFlagAssignments");
                });
#pragma warning restore 612, 618
        }
    }
}
